<a href="https://colab.research.google.com/github/brahmanarman01/Data_Science_Practice/blob/Numpy/builtinfunctionnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr=np.array([2,3,44,33,5])
# result=arr.mean()

result=np.mean(arr)
print(result)

17.4


In [5]:
np.min(arr)

np.int64(2)

In [6]:
print(np.std(arr))

17.6022725805505


In [7]:
print(np.var(arr))

309.84000000000003


In [8]:
print(np.max(arr))

44


In [9]:
print(np.sum(arr))

87


In [10]:
print(np.prod(arr))

43560


In [11]:
print(np.median(arr))

5.0


In [12]:
print(np.percentile(arr, 50))

5.0


In [13]:
print(np.argmin(arr))

0


In [14]:
print(np.argmax(arr))

2


In [15]:
print(np.unique(arr))

[ 2  3  5 33 44]


In [16]:
# Compute the n-th differences of an array.
print(np.diff(arr))

[  1  41 -11 -28]


In [17]:
# Compute the cumulative sum of an array.
print(np.cumsum(arr))

[ 2  5 49 82 87]


In [18]:
# Create an array with evenly spaced numbers over a specified interval.
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [19]:
# Compute the natural logarithm of an array.
print(np.log(arr))

[0.69314718 1.09861229 3.78418963 3.49650756 1.60943791]


In [20]:
# Compute the exponential of an array.
print(np.exp(arr))

[7.38905610e+00 2.00855369e+01 1.28516001e+19 2.14643580e+14
 1.48413159e+02]
