<a href="https://colab.research.google.com/github/brahmanarman01/Data_Science_Practice/blob/Numpy/datatypesnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.array([23,34,5,6,7,4])

In [3]:
# Get the data type of the array
arr.dtype

dtype('int64')

In [4]:
# Change the data type of the array to float64
arr.astype('float64')

array([23., 34.,  5.,  6.,  7.,  4.])

In [8]:
# Create an array with a specified data type (float32)
arr2=np.array([23,4,5,3,6],dtype='float32')
arr2

array([23.,  4.,  5.,  3.,  6.], dtype=float32)

In [9]:
# Create an array of strings with a specified maximum length
arr3=np.array(['apple','banana','cherry'],dtype='U10')
arr3

array(['apple', 'banana', 'cherry'], dtype='<U10')

In [10]:
# Create an array of complex numbers
arr3=np.array([3+9j,1+4j,2+6j],dtype='complex128')
arr3

array([3.+9.j, 1.+4.j, 2.+6.j])

In [ ]:
# This is an empty cell.