<a href="https://colab.research.google.com/github/brahmanarman01/Data_Science_Practice/blob/Numpy/numpy_array_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# Create a NumPy array with 4 rows and 3 columns
arr = np.array([[1,2,3], [4,5,6], [7,8,9],[11,12,13]])
# Display the array
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [2]:
# Flatten the array 'arr' into a 1-dimensional array
flat = arr.flatten()
# Display the flattened array
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [3]:
# Access the element at index 0 of the flattened array 'flat'
flat[0]

np.int64(1)

In [4]:
# Slice the flattened array 'flat' to get elements from the beginning up to index 5 (exclusive)
flat[:5]

array([1, 2, 3, 4, 5])

In [5]:
# Slice the flattened array 'flat' to get elements from index 3 (inclusive) to the end
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [6]:
# Slice the flattened array 'flat' to get elements from index 3 (inclusive) up to index 13 (exclusive)
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [7]:
# Slice the flattened array 'flat' to get elements with a step of 2 (every other element)
flat[::2]

array([ 1,  3,  5,  7,  9, 12])

In [8]:
# Slice the flattened array 'flat' from index 3 to 7 (exclusive) and create a copy
b = flat[3:7].copy() ##+++++++++++++3.
# Display the new array 'b'
b

array([4, 5, 6, 7])

In [9]:
# Change the element at index 0 of array 'b'
b[0] = 4444666

In [10]:
# Display array 'b' after modification
b

array([4444666,       5,       6,       7])

In [11]:
# Display the original flattened array 'flat' to show that changing 'b' did not affect 'flat' (because .copy() was used)
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [12]:
# Create a new NumPy array
arr1 = np.array([1,54,23,2,3,4,30,5,6])
# Use fancy indexing to select elements at indices 1, 4, and 6 from 'arr1'
arr1[[1,4,6]]

array([54,  3, 30])

In [13]:
# Use boolean indexing to select elements from 'arr1' that are greater than 3
arr1[arr1>3]

array([54, 23,  4, 30,  5,  6])