<a href="https://colab.research.google.com/github/brahmanarman01/Data_Science_Practice/blob/Numpy/vectorizationandbroadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# This cell demonstrates a slow way of squaring elements in a NumPy array using a Python loop.
# looping array over python is slow means iteration is slow with large datasets
import numpy as np
arr=np.array([1,2,3,4,5])
result=[]
for num in arr:
  result.append(num**2)
  print(result)

[np.int64(1)]
[np.int64(1), np.int64(4)]
[np.int64(1), np.int64(4), np.int64(9)]
[np.int64(1), np.int64(4), np.int64(9), np.int64(16)]
[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [ ]:
# This cell demonstrates vectorization in NumPy for squaring elements in an array, which is faster than looping.
# vectorization
arr=np.array([1,2,3,4,5])
result=arr**2
print(result)

[ 1  4  9 16 25]


In [ ]:
# This cell demonstrates adding a scalar value to each element of a NumPy array using broadcasting.
result=arr+[1]
result

array([2, 3, 4, 5, 6])

In [ ]:
# This cell demonstrates element-wise addition of two 1D NumPy arrays.
import numpy  as np
arr1=np.array([1,2,3])
arr2=np.array([2,3,4])
result=arr1+arr2
result

array([3, 5, 7])

In [15]:
import numpy  as np
arr1=np.array([[1,2,3],[3,4,5]])
arr2=np.array([2,3,4])
result=arr1+arr2
result


array([[3, 5, 7],
       [5, 7, 9]])

In [16]:
# This cell creates and prints a 2D NumPy array named 'data'.
# It contains three rows and four columns of numerical data.
data = np.array([[1, 2, 3, 10],
                 [4, 5, 6, 11],
                 [7, 8, 9, 12]])
print(data)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
[2.44948974 2.44948974 2.44948974 0.81649658] this is mean
[ 4.  5.  6. 11.] this is std
[[-1.22474487 -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487]]
